### ISSUE TITLE
Applying pretrained weights to 128*128 size image

### ISSUE THREAD

**Issue by Diyago** [ZFTurbo/ZF_UNET_224_Pretrained_Model#11]
You have generated pretrained weights for 224*224 input size, but I have 128*128. How can we use such weights in this situation, but without  padding/upsampling 128*128 images. 
Sorry for silly question - is it worth trying in kaggle salt competition?

**Comment by ZFTurbo** [comment]
Weights in convolution blocks are independent from input shape size. You can change shape: on line 81:
https://github.com/ZFTurbo/ZF_UNET_224_Pretrained_Model/blob/master/zf_unet_224_model.py#L81
to
`inputs = Input((128, 128, INPUT_CHANNELS))`
It should work fine.
