### ISSUE TITLE
Tensorflow problem

### ISSUE THREAD

**Issue by lawlite19** [ZFTurbo/ZF_UNET_224_Pretrained_Model#4]
When I use tensorflow-1.3.0 as backend, I get this kind of error:
```
builtins.ValueError: Dimension 2 in both shapes must be equal, but are 3 and 32 for 'Assign' (op: 'Assign') with input shapes: [3,3,3,32], [3,3,32,3].
```

**Comment by ZFTurbo** [comment]
Can you please post full error message as well with line where error appears?

**Comment by lawlite19** [comment]
Sorry, I made a mistake.

**Comment by lawlite19** [comment]
Hi, 
could you send the pretrained weights for buildings to me. I notice DSTL competition has the task. Thank you very much.
[lawlitewang@gmail.com](lawlitewang@gmail.com)

**Comment by ZFTurbo** [comment]
Weights in DSTL competition was made for model with 20 input channels. They won't fit in current model. I recommend to train from scratch. UNET usually converges very well.

**Comment by lawlite19** [comment]
Ok, thanks for your reply.
